---
- name: restart mysql
  service: name=mysql enabled=yes state=restarted

- name: reload nginx
  service: name=nginx enabled=yes state=restarted

- name: restart supervisor
  service: name=supervisor enabled=yes state=restarted

- name: reload supervisor
  service: name=supervisor enabled=yes state=reloaded
