---
- name: Adding Debian 9 OpenNebula GPG key
  apt_key: url='https://downloads.opennebula.org/repo/repo.key' state=present
  when: ansible_os_family == "Debian" and ansible_distribution_major_version == "9"

- name: Adding Debian 9 OpenNebula repository
  apt_repository: repo='deb https://downloads.opennebula.org/repo/5.8/Debian/9 stable opennebula' state=present
  when: ansible_os_family == "Debian" and ansible_distribution_major_version == "9"

# Install OpenNebula
- name: Installing OpenNebula controller applications
  apt:
    update_cache: yes
    state: present
    name:
      - opennebula
      - opennebula-sunstone
      - opennebula-gate
      - opennebula-flow

# Install OpenNebula ruby gem dependencies (ONE TIME)
- name: Installing OpenNebula ruby gem dependencies
  command: '/usr/share/one/install_gems --yes'
  run_once: true

# NOTE: OpenNebula daemons do NOT start after install, contrary to how most other debian packages behave.
# This is good as we want to set passwords and other configurations before we start OpenNebula for the first time.
