---
# Debian 9 Stretch ONLY

# We use the sury.org PHP repositories which contains many versions of PHP
# All of these versions will be newere than comes stock with debian

# Add sury.org GPG keys
- name: Addding sury.org PHP sources GPG key
  apt_key: url='https://packages.sury.org/php/apt.gpg' state=present

# Add sury.org PHP repositories - Debian 8 Jessie
- name: Adding sury.org PHP sources for Debian 8 Jessie
  apt_repository: repo='deb https://packages.sury.org/php/ jessie main' state=present
  when: ansible_os_family == "Debian" and ansible_distribution_major_version == "8"

# Add sury.org PHP repositories - Debian 9 Stretch
- name: Adding sury.org PHP sources for Debian 9 Stretch
  apt_repository: repo='deb https://packages.sury.org/php/ stretch main' state=present
  when: ansible_os_family == "Debian" and ansible_distribution_major_version == "9"

# Install PHP 7.1
- name: Installing PHP 7.1
  apt:
    update_cache: yes
    state: present
    name:
      - php7.1-bcmath
      - php7.1-bz2
      - php7.1-cli
      - php7.1-common
      - php7.1-curl
      - php7.1-fpm
      - php7.1-gd
      - php7.1-imap
      - php7.1-intl
      - php7.1-json
      - php7.1-ldap
      - php7.1-mbstring
      - php7.1-mcrypt
      - php7.1-mysql
      - php7.1-opcache
      - php7.1-readline
      - php7.1-soap
      - php7.1-sybase
      - php7.1-xml
      - php7.1-zip
