---
# Install nodesource
- name: Installing nodesource for node.js 10x LTS
  command: "{{item}}"
  with_items:
    - curl -o install https://deb.nodesource.com/setup_10.x
    - bash install
  args:
    chdir: /tmp
    creates: /usr/bin/nodejs

# Install NodeJS 10.x LTS
- name: Installing node.js 10x LTS
  apt: name=nodejs state=present
