---

- name: "Make sure the MySQL users are present"
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.pass | default('techie') }}"
    priv: "{{ item.priv | default('*.*:ALL') }}"
    state: "present"
    host: "{{ item.host | default('%') }}"
  with_items: "{{ mysql_users }}"
  no_log: "true"
