---
# Debug
- name: User Debug Details
  debug:
    msg:
      - "User: {{ user }}"
      - "ID: {{ users[user]['id'] }}"
      - "GID: {{ users[user]['gid'] }}"
      - "Groups: {{ user_groups }}"
      #- "Password: {{ users[user]['password'] }}"
