---
# Install nodesource
- name: Installing nodesource for node.js 8x LTS
  command: "{{item}}"
  with_items:
    - curl -o install https://deb.nodesource.com/setup_8.x
    - bash install
  args:
    chdir: /tmp
    creates: /usr/bin/nodejs

# Install NodeJS 8.x LTS
- name: Installing node.js 8x LTS
  apt: name=nodejs state=present
