---
- name: restart haproxy
  service: name=haproxy enabled=yes state=restarted

- name: reload haproxy
  service: name=haproxy enabled=yes state=reloaded

- name: restart rsyslog
  service: name=rsyslog enabled=yes state=restarted
