---
# Copy profiles to /etc/profile.d/
- include_tasks: ../../../functions/copy_etc-profile.d.yml

# Copy scripts to /usr/local/bin
- include_tasks: ../../../functions/copy_usr-local-bin.yml

# Install pyenv
- include_tasks: install-pyenv.yml

# Install python versions
- include_tasks: install-python.yml

