---
# Manjaro Server
# ------------------------------------------------------------------------------
- name: Configuring Manjaro Physical OR Virtual server
  include_tasks: all.yml

# Physical Manjaro Server
# ------------------------------------------------------------------------------
- name: Configuring Manjaro physical server
  include_tasks: physical.yml
  when: type == 'physical'


# Virtual Manjaro Server
# ------------------------------------------------------------------------------
- name: Configuring Manjaro virtual server
  include_tasks: virtual.yml
  when: type == 'virtual'

