---
# Copy ssh client config for superuser user so we can git clone without confirmation
- name: Copying superuser SSH client config
  copy:
    src: 'ssh.config'
    dest: '/home/{{ superuser }}/.ssh/config'
    owner: '{{ superuser }}'
    group: '{{ superuser }}'
    mode: '0644'
