---
# NOTICE: Commands like frappe bench and git clone need to run
# as the superuser user, not root.  The playbook that runs this role
# should be logging in as superuser, using become:yes with superusers ssh key
# Because become:yes all command still run as root, until I use
# become_user: superuser below.

- include_tasks: configure-linux.yml
- include_tasks: configure-mysql.yml
- include_tasks: configure-python.yml
- include_tasks: configure-nodejs.yml
- include_tasks: configure-erpnext.yml
